import siemaDailyIndex from "@/data/siema-index.json";

export interface Painting {
  id: string;
  slug: string;
  title: string;
  s3Key: string;
  year: number;
  medium: string;
  description: string;
  tags: string[];
  width: number;
  height: number;
}

const S3_BASE = "https://com27.s3.eu-west-2.amazonaws.com";

export function paintingUrl(s3Key: string): string {
  if (s3Key.startsWith("/")) return s3Key;
  return `${S3_BASE}/${s3Key}`;
}

const CURATED_PAINTINGS: Painting[] = [
  {
    id: "cosmic-detour",
    slug: "cosmic-detour-through-ancient-ruins",
    title: "Cosmic Detour Through Ancient Ruins",
    s3Key: "siema/cosmic-detour.png",
    year: 2026,
    medium: "Digital Sketch",
    description: "A dreamlike journey through crumbling ancient architecture bathed in cosmic light.",
    tags: ["cosmic", "ruins", "surreal"],
    width: 1672,
    height: 941,
  },
  {
    id: "ilya-board",
    slug: "ilya-sutskever-superintelligence-lab-board",
    title: "Ilya Sutskever's Superintelligence Lab Board",
    s3Key: "siema/ilya-board.png",
    year: 2026,
    medium: "Digital Sketch",
    description: "The whiteboard of a mind at the frontier of machine intelligence.",
    tags: ["ai", "science", "conceptual"],
    width: 1672,
    height: 941,
  },
  {
    id: "somosierra",
    slug: "somosierra-cavalry-charge-through-spain",
    title: "Somosierra Cavalry Charge Through Spain",
    s3Key: "siema/somosierra.png",
    year: 2026,
    medium: "Digital Sketch",
    description: "The legendary charge of Polish light cavalry through the mountain pass of Somosierra, 1808.",
    tags: ["history", "war", "cavalry"],
    width: 1672,
    height: 941,
  },
  {
    id: "emergence-1",
    slug: "emergence-i",
    title: "Emergence I",
    s3Key: "siema/sketch-01a.png",
    year: 2026,
    medium: "Digital Sketch",
    description: "Forms rise from the void — the first gesture of becoming.",
    tags: ["abstract", "emergence"],
    width: 1672,
    height: 941,
  },
  {
    id: "emergence-2",
    slug: "emergence-ii",
    title: "Emergence II",
    s3Key: "siema/sketch-01b.png",
    year: 2026,
    medium: "Digital Sketch",
    description: "Structure coalesces from chaos in the second movement.",
    tags: ["abstract", "emergence"],
    width: 1672,
    height: 941,
  },
  {
    id: "emergence-3",
    slug: "emergence-iii",
    title: "Emergence III",
    s3Key: "siema/sketch-01c.png",
    year: 2026,
    medium: "Digital Sketch",
    description: "The third act — form fully realised from formlessness.",
    tags: ["abstract", "emergence"],
    width: 1672,
    height: 941,
  },
  {
    id: "threshold-1",
    slug: "the-threshold-i",
    title: "The Threshold I",
    s3Key: "siema/sketch-02a.png",
    year: 2026,
    medium: "Digital Sketch",
    description: "Standing at the edge of the knowable world.",
    tags: ["abstract", "liminal"],
    width: 1672,
    height: 941,
  },
  {
    id: "threshold-2",
    slug: "the-threshold-ii",
    title: "The Threshold II",
    s3Key: "siema/sketch-02b.png",
    year: 2026,
    medium: "Digital Sketch",
    description: "The passage beyond all thresholds.",
    tags: ["abstract", "liminal"],
    width: 1672,
    height: 941,
  },
  {
    id: "fragments-1",
    slug: "fragments-of-time-i",
    title: "Fragments of Time I",
    s3Key: "siema/sketch-03a.png",
    year: 2026,
    medium: "Digital Sketch",
    description: "Memory shattered and reassembled into new meaning.",
    tags: ["time", "memory", "abstract"],
    width: 1672,
    height: 941,
  },
  {
    id: "fragments-2",
    slug: "fragments-of-time-ii",
    title: "Fragments of Time II",
    s3Key: "siema/sketch-03b.png",
    year: 2026,
    medium: "Digital Sketch",
    description: "The second fracture — time folding back on itself.",
    tags: ["time", "memory", "abstract"],
    width: 1672,
    height: 941,
  },
  {
    id: "digital-reverie-1",
    slug: "digital-reverie-i",
    title: "Digital Reverie I",
    s3Key: "siema/sketch-04a.png",
    year: 2026,
    medium: "Digital Sketch",
    description: "Dreaming in the language of machines.",
    tags: ["digital", "dream", "abstract"],
    width: 1672,
    height: 941,
  },
  {
    id: "digital-reverie-2",
    slug: "digital-reverie-ii",
    title: "Digital Reverie II",
    s3Key: "siema/sketch-04b.png",
    year: 2026,
    medium: "Digital Sketch",
    description: "The deeper layer of the machine dream.",
    tags: ["digital", "dream", "abstract"],
    width: 1672,
    height: 941,
  },
  {
    id: "neural-pathways-1",
    slug: "neural-pathways-i",
    title: "Neural Pathways I",
    s3Key: "siema/sketch-05a.png",
    year: 2026,
    medium: "Digital Sketch",
    description: "The intricate highways of thought, rendered visible.",
    tags: ["neural", "science", "abstract"],
    width: 1672,
    height: 941,
  },
  {
    id: "neural-pathways-2",
    slug: "neural-pathways-ii",
    title: "Neural Pathways II",
    s3Key: "siema/sketch-05b.png",
    year: 2026,
    medium: "Digital Sketch",
    description: "Deeper circuits — the architecture of consciousness.",
    tags: ["neural", "science", "abstract"],
    width: 1672,
    height: 941,
  },
  {
    id: "abstract-mind-1",
    slug: "abstract-mind-i",
    title: "Abstract Mind I",
    s3Key: "siema/sketch-06a.png",
    year: 2026,
    medium: "Digital Sketch",
    description: "Thought without form — mind without boundary.",
    tags: ["mind", "abstract", "philosophical"],
    width: 1672,
    height: 941,
  },
  {
    id: "abstract-mind-2",
    slug: "abstract-mind-ii",
    title: "Abstract Mind II",
    s3Key: "siema/sketch-06b.png",
    year: 2026,
    medium: "Digital Sketch",
    description: "The second mind — shadow and light in dialogue.",
    tags: ["mind", "abstract", "philosophical"],
    width: 1672,
    height: 941,
  },
  {
    id: "the-nexus",
    slug: "the-nexus",
    title: "The Nexus",
    s3Key: "siema/sketch-07.png",
    year: 2026,
    medium: "Digital Sketch",
    description: "The point where all lines converge.",
    tags: ["convergence", "abstract"],
    width: 1672,
    height: 941,
  },
  {
    id: "convergence",
    slug: "convergence",
    title: "Convergence",
    s3Key: "siema/sketch-08.png",
    year: 2026,
    medium: "Digital Sketch",
    description: "Everything moving toward a single irreducible point.",
    tags: ["convergence", "abstract"],
    width: 1672,
    height: 941,
  },
  {
    id: "dissolution",
    slug: "dissolution",
    title: "Dissolution",
    s3Key: "siema/sketch-09.png",
    year: 2026,
    medium: "Digital Sketch",
    description: "The edge of the defined — where things come undone.",
    tags: ["entropy", "abstract"],
    width: 1672,
    height: 941,
  },
  {
    id: "the-infinite",
    slug: "the-infinite",
    title: "The Infinite",
    s3Key: "siema/sketch-10.png",
    year: 2026,
    medium: "Digital Sketch",
    description: "A contemplation of endlessness — the final work in the series.",
    tags: ["infinity", "abstract", "philosophical"],
    width: 1672,
    height: 941,
  },
];

const GENERATED_PAINTINGS = siemaDailyIndex.paintings as Painting[];
export const PAINTINGS: Painting[] = [...GENERATED_PAINTINGS, ...CURATED_PAINTINGS];

export function getPainting(slug: string): Painting | undefined {
  return PAINTINGS.find((p) => p.slug === slug);
}
